version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/node:18.17  # Ubuntu + Node.js
    working_directory: ~/repo

jobs:
  build:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Build (No-op for static site)
          command: echo "No build step needed"

  sonarcloud-analysis:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip
            export PATH=$PATH:$PWD/sonar-scanner-*/bin
            sonar-scanner

  deploy:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Simulate Deployment
          command: |
            echo "Deploying static site..."
            # Replace this with real deployment (GitHub Pages, S3, Netlify CLI, etc.)

workflows:
  version: 2
  full-pipeline:
    jobs:
      - build
      - sonarcloud-analysis:
          requires:
            - build
      - deploy:
          requires:
            - sonarcloud-analysis
