version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/repo

jobs:
  build:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Build (No-op for static site)
          command: echo "No build step needed"

  sonarcloud-analysis:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Install and Run SonarScanner (inline config)
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip
            export PATH="$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin"

            sonar-scanner \
              -Dsonar.projectKey=deepam-dits \
              -Dsonar.organization=deepam-dits \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.branch.name=main \
              -Dsonar.sources=js \
              -Dsonar.exclusions="css/**,images/**,**/*.html" \
              -Dsonar.login=$SONAR_TOKEN



  deploy:
    executor: ubuntu-executor
    steps:
      - checkout
      - run:
          name: Simulate Deployment
          command: echo "Deploying static site..."

workflows:
  version: 2
  full-pipeline:
    jobs:
      - build
      - sonarcloud-analysis:
          requires:
            - build
      - deploy:
          requires:
            - sonarcloud-analysis
